AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS-Inspector-Quickstart"

Parameters:
  AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/infrastructure/base-ami'
  KeyPair:
    Description: Key pair to launch ec2 instance
    Type: String
    Default: iopp-poc1
  networkStackName:
    Type: String
    Default: cfn02-network
  ec2tag:
    Description: Tag for ec2 instances for scanning
    Type: String
  ScanLength:
    Type: Number
    Description: Duration of Inspector Scan in seconds
    Default: 180
  CommitId:
    Type: String
    Description: Duration of Inspector Scan in seconds

Mappings: 
  RegionMap:
    eu-west-1:
      CommonVul: arn:aws:inspector:eu-west-1:357557129151:rulespackage/0-ubA5XvBh
      CIS: arn:aws:inspector:eu-west-1:357557129151:rulespackage/0-sJBhCr0F
      SecurityBest: arn:aws:inspector:eu-west-1:357557129151:rulespackage/0-SnojL3Z6

Resources:
  inspectorInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref inspectorInstanceIamRole
  inspectorInstanceIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2RoleforSSM"
  InspectorEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: t2.micro
      IamInstanceProfile: !Ref inspectorInstanceProfile
      KeyName: !Ref KeyPair
      SubnetId: {"Fn::ImportValue": !Sub "${networkStackName}-${AWS::Region}-privateAZaId"}  
      Tags:
        - Key: Name
          Value: !Ref ec2tag
      UserData:
        Fn::Base64: |+
          !#/bin/bash
          sudo yum update -y
          sudo yum install -y wget
          wget https://inspector-agent.amazonaws.com/linux/latest/install"
          sudo bash install
          systemctl start amazon-ssm-agent.service
          exit 0

  InspectorResourceGroup:
    Type: AWS::Inspector::ResourceGroup
    Properties: 
      ResourceGroupTags: 
        - Key: Name
          Value: !Ref ec2tag
  InspectorAssessmentTarget:
    Type: AWS::Inspector::AssessmentTarget
    Properties: 
      ResourceGroupArn: !Ref InspectorResourceGroup
  InspectorAssessmentTemplate:
    Type: AWS::Inspector::AssessmentTemplate
    Properties: 
      AssessmentTargetArn: !Ref InspectorAssessmentTarget
      DurationInSeconds: !Ref ScanLength
      RulesPackageArns: 
        - !FindInMap [RegionMap, !Ref "AWS::Region", CommonVul]
        - !FindInMap [RegionMap, !Ref "AWS::Region", CIS]
        - !FindInMap [RegionMap, !Ref "AWS::Region", SecurityBest]
      UserAttributesForFindings: 
        - Key: Name
          Value: !Ref ec2tag
        - Key: StackName
          Value: !Ref "AWS::StackName"
        - Key: CommitId
          Value: !Ref CommitId
        - Key: AMI_ID
          Value: !Ref AMI

Outputs:
  ResourceGroup:
    Description: Inspector Resource Group
    Value: !GetAtt InspectorResourceGroup.Arn
  AssessmentTarget:
    Description: Inspector Assessment Target
    Value: !GetAtt InspectorAssessmentTarget.Arn
  AssessmentTemplate:
    Description: Inspector Assessment Template
    Value: !GetAtt InspectorAssessmentTemplate.Arn
  CommitId:
    Description: Commit Id
    Value: !Ref CommitId