version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update -y
      - apt-get install wget unzip -y   
      - echo "Installing Packer"
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip && unzip packer.zip
      - chown root:root packer && chown 777 packer
      - echo "Validating Packer template" 
      - ./packer validate packer-files/iopp-base-centos.json     
      - pip install --upgrade pip
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Packer build"
      - ./packer build -var 'created_by=codepipeline' -var "branch_name=$BRANCH_NAME" packer-files/iopp-base-centos.json
